---
lr_schedulers:
  training_lr:
    class: MultiStepLR
    milestones: [100, 150, 200]
    gamma: 0.5

policies:
  - lr_scheduler:
      instance_name: training_lr
    starting_epoch: 0
    ending_epoch: 250
    frequency: 1
